[package]
name = "whatwg-infra"
version = "0.1.0"
authors = [
	"Samantha Nguyen, <contact@samanthanguyen.me>",
]
description = "Tiny Rust-based implementation of the WHATWG Infra Standard"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.63.0"
